name: Build and Release PrestaShop Module

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare module folder
        run: |
          MODULE_NAME="paydo"
          ARCHIVE_NAME="paydo.zip"

          mkdir "${MODULE_NAME}"
          rsync -av --exclude='.git*' --exclude='.github' --exclude='*.zip' --exclude='release.sh' ./ "${MODULE_NAME}/"

          zip -r "${ARCHIVE_NAME}" "${MODULE_NAME}"

          echo "ARCHIVE_NAME=${ARCHIVE_NAME}" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.ARCHIVE_NAME }}
          fail_on_unmatched_files: true
          body: "🔹 New release for PrestaShop module\n\n✅ Version: ${{ github.ref_name }}"
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
